/**
 * Agent 活动流：事件 → 用户可见文案映射（设计附录 A / B）。
 *
 * 红线（§3.1）：只取 safePayload 里的计数/ID/状态等结构化字段，
 * 字符串值一律本地映射。绝不把模型原文或 safePayload 的字符串值
 * 直接拼进文案。未知工具/角色按安全回退（"工具"/"代理"），不报错。
 */

import type { AgentEventView } from "@/lib/api";
import { isRecord } from "./note-editor-utils";

export type AgentEventRowStatus = "running" | "success" | "failed" | "warning" | "muted";

export interface AgentEventRowView {
  /** 前端渲染文案（固定中文模板，不含原始 payload 字符串值） */
  text: string;
  /** 状态点：进行中/成功/失败/警告/静默 */
  status: AgentEventRowStatus;
  /** 角色中文名（无角色时为 null） */
  roleLabel: string | null;
}

/** 角色中文名（附录 B）。未知角色返回 null，由调用方回退。 */
export function agentRoleLabel(role: string | null | undefined): string | null {
  if (!role) return null;
  return ROLE_LABELS[role] ?? null;
}

/** 工具中文名（附录 B 分组）。未知工具名安全回退为「工具」。 */
export function agentToolLabel(toolName: string | null | undefined): string {
  if (!toolName) return "工具";
  return TOOL_LABELS[toolName] ?? toolName;
}

/**
 * 事件 → 文案映射。
 *
 * 仅依赖 worker 实际写入的 5 种 eventType 字面量
 * （tool_request / tool_result / turn_completed / pagination_event /
 * validation_event）。其余（枚举里的 "aspirational" 类型）统一安全回退。
 */
export function agentEventRowText(event: AgentEventView): AgentEventRowView {
  const roleLabel = agentRoleLabel(event.agentRole);
  const payload = isRecord(event.safePayload) ? event.safePayload : {};
  switch (event.eventType) {
    case "tool_request":
      return toolRequestRow(event, payload, roleLabel);
    case "tool_result":
      return toolResultRow(event, payload, roleLabel);
    case "turn_completed":
      return turnCompletedRow(event, payload);
    case "pagination_event":
      return paginationRow(payload);
    case "validation_event":
      return validationRow(payload);
    default:
      return { text: "代理活动更新", status: "muted", roleLabel };
  }
}

// ─── 角色映射（附录 B） ─────────────────────────────────────────────

const ROLE_LABELS: Record<string, string> = {
  generation_supervisor: "总控 Supervisor",
  text_extractor: "文本提取专家",
  code_extractor: "代码/公式专家",
  vision_specialist: "视觉专家",
  deck_composer: "卡组编排专家",
  grounding_critic: "引用校验评论家",
  repairer: "修复专家",
};

// ─── 工具映射（附录 B，按分组） ─────────────────────────────────────

const TOOL_LABELS: Record<string, string> = {
  // 委派
  delegate_specialist: "委派子代理",
  // 读取
  get_run_manifest: "读取任务清单",
  get_next_unassigned_bundles: "领取未分配素材",
  read_agent_task_results: "读取子代理结果",
  read_assigned_bundles: "读取已分配素材",
  read_candidate_ledger: "读取候选账本",
  read_quality_report: "读取质量报告",
  read_draft: "读取卡组草稿",
  read_candidates: "读取候选",
  read_evidence: "读取证据",
  read_issues: "读取问题清单",
  // 检索
  search_related_evidence: "检索相关证据",
  ensure_semantic_index: "建立语义索引",
  // 写入
  record_extraction_decisions: "记录提取决策",
  apply_candidate_operations: "应用候选操作",
  submit_deck_draft: "提交卡组草稿",
  submit_deck_proposal: "提交卡组提案",
  apply_draft_patch: "应用草稿补丁",
  submit_draft_patch: "提交草稿补丁",
  submit_quality_report: "提交质量报告",
  complete_agent_task: "完成任务",
  // 校验
  validate_draft: "校验卡组草稿",
  request_verification: "请求校验",
  request_grounding_review: "请求引用评论",
  request_repair: "请求修复",
};

// ─── 自动兜底 reason 映射（supervisor-auto-fallback.ts） ─────────────

const AUTO_PROGRESS_REASONS: Record<string, string> = {
  supervisor_no_tool_calls_auto_progress: "模型未调用工具，系统按管道状态自动推进",
  supervisor_model_verification_redirect: "模型请求校验，系统已转向校验流程",
  supervisor_read_only_spin_detected: "检测到连续只读轮询，系统自动推进",
};

function num(payload: Record<string, unknown>, key: string): number | null {
  const v = payload[key];
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

function toolRequestRow(
  event: AgentEventView,
  payload: Record<string, unknown>,
  roleLabel: string | null,
): AgentEventRowView {
  if (payload.autoGenerated === true) {
    const reason = typeof payload.reason === "string"
      ? AUTO_PROGRESS_REASONS[payload.reason]
      : null;
    return {
      text: reason ? `系统自动推进：${reason}` : "系统自动推进",
      status: "muted",
      roleLabel,
    };
  }
  const args = isRecord(payload.args) ? payload.args : {};
  if (event.toolName === "delegate_specialist") {
    const subRole = typeof args.role === "string" ? args.role : null;
    const subLabel = subRole ? (agentRoleLabel(subRole) ?? subRole) : "子代理";
    const bundleCount = Array.isArray(args.bundleIds) ? args.bundleIds.length : null;
    const countText = bundleCount != null ? `处理 ${bundleCount} 个素材` : "";
    return {
      text: `委派「${subLabel}」${countText}`.trim(),
      status: "running",
      roleLabel,
    };
  }
  return {
    text: `调用「${agentToolLabel(event.toolName)}」`,
    status: "running",
    roleLabel,
  };
}

function toolResultRow(
  event: AgentEventView,
  payload: Record<string, unknown>,
  roleLabel: string | null,
): AgentEventRowView {
  // 失败结果：优先展示工具名 + 失败。
  if (payload.success === false) {
    return {
      text: `「${agentToolLabel(event.toolName)}」执行失败`,
      status: "failed",
      roleLabel,
    };
  }

  switch (event.toolName) {
    case "delegate_specialist": {
      const result = isRecord(payload.result) ? payload.result : {};
      const subRole = typeof result.role === "string" ? result.role : null;
      const subLabel = subRole ? (agentRoleLabel(subRole) ?? subRole) : "子代理";
      return { text: `子代理「${subLabel}」已就绪`, status: "success", roleLabel };
    }
    case "record_extraction_decisions": {
      const added = num(payload, "candidateCount");
      const rejected = num(payload, "noCandidateCount");
      const parts: string[] = [];
      if (added != null) parts.push(`新增 ${added} 候选`);
      if (rejected != null && rejected > 0) parts.push(`拒绝 ${rejected} 条`);
      return {
        text: `记录提取决策${parts.length > 0 ? ` · ${parts.join(" / ")}` : ""}`,
        status: "success",
        roleLabel,
      };
    }
    case "complete_agent_task": {
      const sub = roleLabel ?? "子代理";
      return { text: `完成「${sub}」任务`, status: "success", roleLabel };
    }
    case "submit_deck_proposal": {
      const cardCount = num(payload, "cardCount");
      const deckTitle = typeof payload.deckTitle === "string" ? payload.deckTitle : null;
      const parts = ["提交卡组提案"];
      if (cardCount != null) parts.push(`${cardCount} 张`);
      if (deckTitle) parts.push(`（${deckTitle}）`);
      return { text: parts.join(" · "), status: "success", roleLabel };
    }
    case "submit_quality_report": {
      const criticStatus = typeof payload.criticStatus === "string" ? payload.criticStatus : null;
      const hard = num(payload, "hardIssueCount");
      const soft = num(payload, "softIssueCount");
      const statusText = criticStatus === "passed"
        ? "通过"
        : criticStatus === "failed"
          ? "未通过"
          : null;
      const parts: string[] = [];
      if (statusText) parts.push(statusText);
      if (hard != null) parts.push(`硬 ${hard}`);
      if (soft != null) parts.push(`软 ${soft}`);
      return {
        text: `Critic 结论：${parts.join(" · ")}`,
        status: criticStatus === "failed" ? "warning" : "success",
        roleLabel,
      };
    }
    case "submit_draft_patch": {
      const patchCount = num(payload, "patchCount");
      return {
        text: patchCount != null ? `应用修复补丁 · ${patchCount} 处` : "应用修复补丁",
        status: "success",
        roleLabel,
      };
    }
    default: {
      // verify / publish 等无 toolName 或通用结果的里程碑事件。
      // verify 事件（agentRole=null，safePayload 含 passed/checks）。
      if (event.toolName == null) {
        const passed = payload.passed === true;
        const checks = Array.isArray(payload.checks) ? payload.checks as Array<{ passed?: unknown }> : [];
        if (checks.length > 0) {
          const passedCount = checks.filter((c) => c.passed === true).length;
          return {
            text: passed ? `校验通过 ${passedCount}/${checks.length}` : `校验未通过 ${passedCount}/${checks.length}`,
            status: passed ? "success" : "failed",
            roleLabel,
          };
        }
        // publish 里程碑：{cardSetId, cardCount}
        const cardCount = num(payload, "cardCount");
        if (cardCount != null) {
          return { text: `发布卡组 · ${cardCount} 张`, status: "success", roleLabel };
        }
        return { text: "阶段里程碑完成", status: "success", roleLabel };
      }
      return { text: `「${agentToolLabel(event.toolName)}」执行完成`, status: "success", roleLabel };
    }
  }
}

function turnCompletedRow(
  event: AgentEventView,
  payload: Record<string, unknown>,
): AgentEventRowView {
  // prepare 变体：{bundleCount, coverage}（agentRole=null, turnNo=0）
  const bundleCount = num(payload, "bundleCount");
  if (bundleCount != null) {
    return { text: `素材准备完成 · ${bundleCount} 个`, status: "muted", roleLabel: null };
  }
  const turnNo = typeof event.turnNo === "number" ? event.turnNo : null;
  const toolCallCount = num(payload, "toolCallCount");
  const nextAction = typeof payload.nextAction === "string" ? payload.nextAction : null;
  const childTaskIds = Array.isArray(payload.childTaskIds) ? payload.childTaskIds : [];
  let text = turnNo != null ? `第 ${turnNo} 轮完成` : "本轮完成";
  if (toolCallCount != null) text += ` · ${toolCallCount} 次调用`;
  if (nextAction === "wait_for_children" && childTaskIds.length > 0) {
    text += ` · 等待 ${childTaskIds.length} 个子代理`;
  }
  return { text, status: "muted", roleLabel: null };
}

function paginationRow(payload: Record<string, unknown>): AgentEventRowView {
  // extractor 变体：{pageIndex, totalPages, bundleCount, candidateCount, noCandidateCount}
  const pageIndex = num(payload, "pageIndex");
  const totalPages = num(payload, "totalPages");
  if (pageIndex != null && totalPages != null) {
    return {
      text: `正在处理素材 ${pageIndex + 1}/${totalPages}`,
      status: "running",
      roleLabel: null,
    };
  }
  // critic 变体：{batchIndex, totalBatches, candidateCount, verdictCount}
  const batchIndex = num(payload, "batchIndex");
  const totalBatches = num(payload, "totalBatches");
  if (batchIndex != null && totalBatches != null) {
    return {
      text: `正在校验候选 ${batchIndex + 1}/${totalBatches}`,
      status: "running",
      roleLabel: null,
    };
  }
  return { text: "处理中", status: "running", roleLabel: null };
}

function validationRow(payload: Record<string, unknown>): AgentEventRowView {
  const reason = typeof payload.reason === "string" ? payload.reason : null;
  if (reason === "invalid_candidate_provenance") {
    const rejected = num(payload, "rejectedCount");
    const total = num(payload, "totalCount");
    const text = rejected != null && total != null
      ? `拒绝 ${rejected}/${total} 条无效候选`
      : "拒绝无效候选";
    return { text, status: "warning", roleLabel: null };
  }
  if (reason === "no_valid_evidence_for_bundle") {
    return { text: "素材无有效证据，跳过", status: "warning", roleLabel: null };
  }
  return { text: "校验提示", status: "warning", roleLabel: null };
}
