/**
 * Phase B：Agent 事件 → 中文文案映射 + 游标去重单元测试。
 *
 * 覆盖设计附录 A 的每个模板 + 附录 B 角色/工具映射，
 * 以及 useGenerationActivity 的 mergeAgentEvents 去重/上限逻辑。
 */

import assert from "node:assert/strict";
import { describe, it } from "node:test";
import type { AgentEventView } from "../../lib/api-types.ts";
import { agentEventRowText, agentRoleLabel, agentToolLabel } from "../../components/note-editor/agent-event-text.ts";
import { mergeAgentEvents } from "../../components/note-editor/useGenerationActivity.ts";
import { currentGenerationTask } from "../../components/note-editor/GenerationRunSummary.tsx";
import { rowDisplayStatus } from "../../components/note-editor/AgentStreamList.tsx";
import { advanceEta } from "../../components/note-editor/note-editor-utils.ts";
import type { CardGenerationRunView } from "../../lib/api-types.ts";

function event(partial: Partial<AgentEventView>): AgentEventView {
  return {
    id: "evt-1",
    eventKey: "evt-1",
    eventType: "tool_request",
    agentRole: null,
    turnNo: null,
    attemptNo: null,
    toolName: null,
    toolVersion: null,
    unitId: null,
    parentUnitId: null,
    childUnitId: null,
    errorCode: null,
    messageCode: "evt-1",
    safePayload: {},
    createdAt: "2026-08-06T08:00:00.000Z",
    ...partial,
  };
}

describe("agentRoleLabel / agentToolLabel（附录 B）", () => {
  it("映射全部 7 个角色", () => {
    assert.equal(agentRoleLabel("generation_supervisor"), "总控 Supervisor");
    assert.equal(agentRoleLabel("text_extractor"), "文本提取专家");
    assert.equal(agentRoleLabel("code_extractor"), "代码/公式专家");
    assert.equal(agentRoleLabel("vision_specialist"), "视觉专家");
    assert.equal(agentRoleLabel("deck_composer"), "卡组编排专家");
    assert.equal(agentRoleLabel("grounding_critic"), "引用校验评论家");
    assert.equal(agentRoleLabel("repairer"), "修复专家");
  });

  it("未知角色返回 null（安全回退）", () => {
    assert.equal(agentRoleLabel("some_future_role"), null);
    assert.equal(agentRoleLabel(null), null);
  });

  it("未知工具名原样返回（不做报错）", () => {
    assert.equal(agentToolLabel("ensure_semantic_index"), "建立语义索引");
    assert.equal(agentToolLabel(null), "工具");
  });
});

describe("agentEventRowText — tool_request", () => {
  it("委派子代理：显示子角色与素材数", () => {
    const view = agentEventRowText(event({
      eventType: "tool_request",
      agentRole: "generation_supervisor",
      toolName: "delegate_specialist",
      safePayload: { args: { role: "text_extractor", bundleIds: ["b1", "b2", "b3"] } },
    }));
    assert.equal(view.text, "委派「文本提取专家」处理 3 个素材");
    assert.equal(view.status, "running");
    assert.equal(view.roleLabel, "总控 Supervisor");
  });

  it("普通工具调用", () => {
    const view = agentEventRowText(event({
      eventType: "tool_request",
      toolName: "ensure_semantic_index",
      safePayload: { args: {} },
    }));
    assert.equal(view.text, "调用「建立语义索引」");
    assert.equal(view.status, "running");
  });

  it("autoGenerated 兜底：映射 reason，不泄漏原始字符串", () => {
    const view = agentEventRowText(event({
      eventType: "tool_request",
      agentRole: "generation_supervisor",
      toolName: "complete_agent_task",
      safePayload: { autoGenerated: true, reason: "supervisor_no_tool_calls_auto_progress" },
    }));
    assert.ok(view.text.includes("系统自动推进"));
    assert.equal(view.status, "muted");
  });

  it("未知 autoGenerated reason 不泄漏", () => {
    const view = agentEventRowText(event({
      eventType: "tool_request",
      safePayload: { autoGenerated: true, reason: "model_raw_output_xyz" },
    }));
    assert.equal(view.text, "系统自动推进");
  });
});

describe("agentEventRowText — tool_result", () => {
  it("子代理就绪", () => {
    const view = agentEventRowText(event({
      eventType: "tool_result",
      agentRole: "generation_supervisor",
      toolName: "delegate_specialist",
      safePayload: { success: true, result: { role: "code_extractor", status: "assigned" } },
    }));
    assert.equal(view.text, "子代理「代码/公式专家」已就绪");
    assert.equal(view.status, "success");
  });

  it("记录提取决策：新增候选与拒绝计数", () => {
    const view = agentEventRowText(event({
      eventType: "tool_result",
      agentRole: "text_extractor",
      toolName: "record_extraction_decisions",
      safePayload: { success: true, candidateCount: 5, noCandidateCount: 2 },
    }));
    assert.equal(view.text, "记录提取决策 · 新增 5 候选 / 拒绝 2 条");
    assert.equal(view.status, "success");
  });

  it("Critic 结论：通过", () => {
    const view = agentEventRowText(event({
      eventType: "tool_result",
      agentRole: "grounding_critic",
      toolName: "submit_quality_report",
      safePayload: { success: true, criticStatus: "passed", hardIssueCount: 0, softIssueCount: 1 },
    }));
    assert.equal(view.text, "Critic 结论：通过 · 硬 0 · 软 1");
    assert.equal(view.status, "success");
  });

  it("Critic 结论：未通过 → warning", () => {
    const view = agentEventRowText(event({
      eventType: "tool_result",
      agentRole: "grounding_critic",
      toolName: "submit_quality_report",
      safePayload: { success: true, criticStatus: "failed", hardIssueCount: 2, softIssueCount: 1 },
    }));
    assert.equal(view.status, "warning");
  });

  it("提交卡组提案", () => {
    const view = agentEventRowText(event({
      eventType: "tool_result",
      agentRole: "deck_composer",
      toolName: "submit_deck_proposal",
      safePayload: { success: true, cardCount: 12, deckTitle: "数据结构" },
    }));
    assert.ok(view.text.includes("提交卡组提案"));
    assert.ok(view.text.includes("12 张"));
    assert.equal(view.status, "success");
  });

  it("应用修复补丁", () => {
    const view = agentEventRowText(event({
      eventType: "tool_result",
      agentRole: "repairer",
      toolName: "submit_draft_patch",
      safePayload: { success: true, patchCount: 3 },
    }));
    assert.equal(view.text, "应用修复补丁 · 3 处");
  });

  it("工具执行失败 → failed", () => {
    const view = agentEventRowText(event({
      eventType: "tool_result",
      agentRole: "text_extractor",
      toolName: "search_related_evidence",
      safePayload: { success: false, error: "provider_unavailable" },
    }));
    assert.equal(view.text, "「检索相关证据」执行失败");
    assert.equal(view.status, "failed");
  });

  it("verify 事件（无 toolName，checks 数组）", () => {
    const view = agentEventRowText(event({
      eventType: "tool_result",
      agentRole: null,
      toolName: null,
      safePayload: { passed: true, checks: [{ name: "a", passed: true }, { name: "b", passed: true }] },
    }));
    assert.equal(view.text, "校验通过 2/2");
    assert.equal(view.status, "success");
  });

  it("publish 里程碑（cardCount）", () => {
    const view = agentEventRowText(event({
      eventType: "tool_result",
      agentRole: null,
      toolName: null,
      safePayload: { success: true, cardCount: 8 },
    }));
    assert.ok(view.text.includes("发布卡组"));
  });
});

describe("agentEventRowText — turn_completed / pagination / validation", () => {
  it("turn_completed：轮次 + 调用数 + 等待子代理", () => {
    const view = agentEventRowText(event({
      eventType: "turn_completed",
      turnNo: 1,
      safePayload: { finishReason: "tool_calls", toolCallCount: 2, nextAction: "wait_for_children", childTaskIds: ["c1", "c2"] },
    }));
    assert.equal(view.text, "第 1 轮完成 · 2 次调用 · 等待 2 个子代理");
    assert.equal(view.status, "muted");
  });

  it("turn_completed：prepare 变体（bundleCount）", () => {
    const view = agentEventRowText(event({
      eventType: "turn_completed",
      safePayload: { bundleCount: 12, coverage: 0.5 },
    }));
    assert.equal(view.text, "素材准备完成 · 12 个");
  });

  it("pagination_event：extractor 变体", () => {
    const view = agentEventRowText(event({
      eventType: "pagination_event",
      safePayload: { pageIndex: 0, totalPages: 4, bundleCount: 3, candidateCount: 5, noCandidateCount: 0 },
    }));
    assert.equal(view.text, "正在处理素材 1/4");
    assert.equal(view.status, "running");
  });

  it("pagination_event：critic 变体", () => {
    const view = agentEventRowText(event({
      eventType: "pagination_event",
      safePayload: { batchIndex: 1, totalBatches: 3, candidateCount: 10, verdictCount: 4 },
    }));
    assert.equal(view.text, "正在校验候选 2/3");
  });

  it("validation_event：invalid_candidate_provenance", () => {
    const view = agentEventRowText(event({
      eventType: "validation_event",
      safePayload: { reason: "invalid_candidate_provenance", rejectedCount: 3, totalCount: 10, details: [] },
    }));
    assert.equal(view.text, "拒绝 3/10 条无效候选");
    assert.equal(view.status, "warning");
  });

  it("validation_event：no_valid_evidence_for_bundle", () => {
    const view = agentEventRowText(event({
      eventType: "validation_event",
      safePayload: { reason: "no_valid_evidence_for_bundle", localId: "l1", bundleId: "b1", evidenceRefIds: [] },
    }));
    assert.equal(view.text, "素材无有效证据，跳过");
  });

  it("未知 eventType 安全回退", () => {
    const view = agentEventRowText(event({ eventType: "turn_started" }));
    assert.equal(view.text, "代理活动更新");
    assert.equal(view.status, "muted");
  });
});

describe("mergeAgentEvents — 去重与上限", () => {
  function ev(key: string): AgentEventView {
    return event({ eventKey: key, id: key, messageCode: key });
  }

  it("增量合并不产生重复事件", () => {
    const buffer = [ev("a"), ev("b")];
    const merged = mergeAgentEvents(buffer, [ev("b"), ev("c")], new Set());
    assert.deepEqual(merged.map((e) => e.eventKey), ["a", "b", "c"]);
  });

  it("超出上限丢弃最早事件", () => {
    const buffer = [ev("a"), ev("b")];
    const merged = mergeAgentEvents(buffer, [ev("c")], new Set(), 2);
    assert.deepEqual(merged.map((e) => e.eventKey), ["b", "c"]);
  });

  it("空增量返回原缓冲", () => {
    const buffer = [ev("a")];
    assert.equal(mergeAgentEvents(buffer, [], new Set()), buffer);
  });

  it("StrictMode 双调用更新函数不丢事件（回归）", () => {
    // React 19 dev（StrictMode）会以同一 prev 调用两次 setState 更新函数，
    // 用于检测不纯。如果合并逻辑依赖"seen 被副作用填充"，第二次调用会
    // 把结果清空，导致执行记录永远不显示。合并函数必须对入参只读。
    const buffer = [ev("a")];
    const page = [ev("b"), ev("c")];
    const seen = new Set<string>();
    // 第一次调用（React 内部 double-invoke 的第一遍）
    const r1 = mergeAgentEvents(buffer, page, seen);
    // 第二次调用：同一 prev + 同一 seen（合并函数不得修改 seen）
    const r2 = mergeAgentEvents(buffer, page, seen);
    assert.deepEqual(
      r1.map((e) => e.eventKey),
      ["a", "b", "c"],
      "第一次调用应正常合并",
    );
    assert.deepEqual(
      r2.map((e) => e.eventKey),
      ["a", "b", "c"],
      "第二次调用（同一入参）结果必须一致，不能因 seen 副作用清空",
    );
  });
});

describe("currentGenerationTask — 当前任务随活动流变化", () => {
  function runWith(stage: string | null): CardGenerationRunView {
    return {
      runId: "run-1",
      noteId: "note-1",
      noteVersionId: "nv-1",
      status: "running",
      stage: "running",
      stateVersion: 0,
      sequence: 1,
      engineMode: "supervisor_agent_v1",
      shellVersion: "v1",
      shellStage: stage,
      sourceSnapshot: { noteVersionId: "nv-1", versionNo: 3, contentHash: "h" },
      progress: { completed: 0, total: 100, unit: "percent" },
      coverage: {
        sourceUnitsCompleted: 0, sourceUnitsTotal: 1,
        imagesCompleted: 0, imagesTotal: 0,
        sourceCoverageBps: 0, imageCoverageBps: 10_000,
      },
      warnings: [],
      actions: { retryable: false, restartable: false, cancellable: true },
      result: null,
      error: null,
      createdAt: "2026-01-01T00:00:00Z",
      startedAt: null,
      finishedAt: null,
    };
  }

  it("有 running 事件时用事件文案描述当前任务", () => {
    const task = currentGenerationTask(
      runWith("generating"),
      event({
        eventType: "tool_request",
        eventKey: "e1",
        toolName: "delegate_specialist",
        agentRole: "generation_supervisor",
        turnNo: 2,
        safePayload: { args: { role: "text_extractor", bundleIds: ["a", "b", "c"] } },
      }),
    );
    assert.ok(task.title.startsWith("正在"), "进行中动作应加'正在'前缀");
    assert.ok(task.title.includes("委派"), "应包含事件动作文案");
    assert.ok(task.copy.includes("执行中"), "进行中应标记'执行中'");
  });

  it("有已完成事件时直接展示动作结果", () => {
    const task = currentGenerationTask(
      runWith("generating"),
      event({
        eventType: "tool_result",
        eventKey: "e2",
        toolName: "record_extraction_decisions",
        agentRole: "generation_supervisor",
        safePayload: { success: true, result: { candidateCount: 5 } },
      }),
    );
    assert.ok(!task.title.startsWith("正在"), "已完成事件不加'正在'前缀");
    assert.ok(task.title.includes("记录提取决策"), "应包含动作文案");
    assert.ok(task.copy.includes("已完成"), "已完成应标记'已完成'");
  });

  it("无事件时回退到阶段文案", () => {
    const task = currentGenerationTask(runWith("checking"), null);
    assert.equal(task.title, "正在检查结果质量");
    assert.equal(currentGenerationTask(runWith("preparing"), null).title, "正在理解这篇笔记");
    assert.equal(currentGenerationTask(runWith(null), null).title, "正在设计可回忆的问题");
  });
});

describe("rowDisplayStatus — 最新一行转圈，被取代的 running 改打勾", () => {
  it("最新一行始终转圈（除失败/警告）", () => {
    assert.equal(rowDisplayStatus("running", true), "running");
    assert.equal(rowDisplayStatus("success", true), "running");
    assert.equal(rowDisplayStatus("muted", true), "running");
  });

  it("最新一行为失败/警告时保留原状", () => {
    assert.equal(rowDisplayStatus("failed", true), "failed");
    assert.equal(rowDisplayStatus("warning", true), "warning");
  });

  it("非最新 running 事件视为已完成（打勾）", () => {
    assert.equal(rowDisplayStatus("running", false), "success");
  });

  it("非 latest 时其它状态原样保留", () => {
    assert.equal(rowDisplayStatus("success", false), "success");
    assert.equal(rowDisplayStatus("failed", false), "failed");
    assert.equal(rowDisplayStatus("warning", false), "warning");
    assert.equal(rowDisplayStatus("muted", false), "muted");
  });
});

describe("advanceEta — 预计剩余基于推进速率，不随 elapsed 单调膨胀", () => {
  it("percent 未到 15 时不估算（返回 null，不推进）", () => {
    const r = advanceEta(10, 60, null, null);
    assert.equal(r.remainingSeconds, null);
    assert.equal(r.sample, null);
    assert.equal(r.rate, null);
  });

  it("percent 100 时剩余为 0", () => {
    const r = advanceEta(100, 300, { elapsed: 240, percent: 80 }, 0.2);
    assert.equal(r.remainingSeconds, 0);
  });

  it("首个样本只记录，尚无速率 → 计算中", () => {
    const r = advanceEta(26, 30, null, null);
    assert.equal(r.remainingSeconds, null);
    assert.deepEqual(r.sample, { elapsed: 30, percent: 26 });
    assert.equal(r.rate, null);
  });

  it("percent 停留期间不推进样本，剩余时间保持不变（不虚涨）", () => {
    // 首次推进：样本 (30, 26)，速率未知
    const first = advanceEta(26, 30, null, null);
    // 二次推进：26→37，耗时 30s（30→60），速率 11/30 ≈ 0.367 %/s
    const jump = advanceEta(37, 60, first.sample, first.rate);
    assert.ok(jump.rate != null && jump.rate > 0);
    const etaAfterJump = jump.remainingSeconds;
    // percent 停在 37，elapsed 从 60 涨到 180：速率保持 → 剩余不变
    const stuck = advanceEta(37, 180, jump.sample, jump.rate);
    assert.equal(stuck.sample, jump.sample, "档位之间不推进样本");
    assert.equal(stuck.rate, jump.rate, "档位之间速率保持");
    assert.equal(stuck.remainingSeconds, etaAfterJump, "剩余时间不随 elapsed 膨胀");
  });

  it("再次推进时用 EWMA 平滑速率并更新剩余", () => {
    const first = advanceEta(26, 30, null, null); // 样本 (30, 26)
    const jump = advanceEta(37, 60, first.sample, null); // 26→37, dt=30 → rate=11/30
    assert.ok(jump.rate != null);
    const next = advanceEta(48, 120, jump.sample, jump.rate); // dp=11, dt=60 → instant≈0.183
    const expectedRate = jump.rate * 0.7 + (11 / 60) * 0.3;
    assert.ok(Math.abs((next.rate ?? 0) - expectedRate) < 1e-6, "速率应为 EWMA 平滑");
    assert.deepEqual(next.sample, { elapsed: 120, percent: 48 });
    assert.ok(next.remainingSeconds != null && next.remainingSeconds > 0);
  });
});
