export const PET_IPC_CHANNELS = {
  getCapabilities: "pet:get-capabilities",
  getDeviceSessionId: "pet:get-device-session-id",
  getWindowState: "pet:get-window-state",
  registerHitGeometry: "pet:register-hit-geometry",
  setInteractionMode: "pet:set-interaction-mode",
  requestTextInputFocus: "pet:request-text-input-focus",
  releaseTextInputFocus: "pet:release-text-input-focus",
  setPetModeEnabled: "pet:set-mode-enabled",
  setAlwaysOnTop: "pet:set-always-on-top",
  setLocked: "pet:set-locked",
  dragBy: "pet:drag-by",
  setPetScale: "pet:set-scale",
  setPrivacyMode: "pet:set-privacy-mode",
  moveToSafePosition: "pet:move-to-safe-position",
  openMainRoute: "pet:open-main-route",
  reportBootstrap: "pet:report-bootstrap",
  hidePet: "pet:hide",
  windowStateChanged: "pet:window-state-changed",
  lifecycleEvent: "pet:lifecycle-event",
  openExternal: "desktop:open-external",
  getVersion: "desktop:get-version",
  // 2026-08-12：设置页（main window）桌宠开关
  desktopGetPetMode: "desktop:get-pet-mode",
  desktopSetPetMode: "desktop:set-pet-mode",
} as const;
