/**
 * v0.6 Question/Rubric Gold v1 数据集 (计划 §4.2)
 *
 * 计划要求：
 *   - ≥ 60 个跨领域 key point
 *   - 标签：题型适配、答案泄漏、rubric 完整性、证据支持、人工接受
 *   - RC 建议门槛：
 *     schema/ref 完整性 100%
 *     答案泄漏 0
 *     hard-evidence support precision ≥ 95%
 *     人工接受率 ≥ 85%
 *
 * 注意：本文件为 fixture 基础设施，包含代表性样本。
 * 真实人工标注需由 ≥ 2 人独立完成高风险样本并记录分歧解决。
 * 样本不足时写 `insufficient_data`，不能包装为通过。
 */

import type { QuestionRubricGoldSample } from "./types.ts";

export const QUESTION_RUBRIC_GOLD_VERSION = "2026-07-25-v1";
export const QUESTION_RUBRIC_GOLD_MINIMUM_SIZE = 60;

// ─── 领域分布 ─────────────────────────────────────────────────────────────
// 10 个领域，每个领域 6 个样本 = 60 个 key point

const DOMAINS = [
  "distributed-systems",
  "data-structures",
  "machine-learning",
  "web-security",
  "database-design",
  "network-protocols",
  "software-architecture",
  "concurrency",
  "cloud-computing",
  "testing-qa",
] as const;

// ─── 样本工厂 ─────────────────────────────────────────────────────────────

function makeSample(
  id: string,
  domain: string,
  claim: string,
  quote: string,
  questionType: "explain" | "example" | "apply",
  expectedQuestion: string,
  rubricItems: Array<{
    key: string;
    criterion: string;
    expectedConcept: string;
    weight: 1 | 2 | 3;
    required: boolean;
  }>,
  humanAccepted: boolean = true,
  leakageReason: string | null = null,
): QuestionRubricGoldSample {
  return {
    id,
    domain,
    claim,
    quote,
    questionType,
    expectedQuestion,
    expectedRubricItems: rubricItems.map((r, i) => ({
      ...r,
      evidenceRefId: `ev-ref-${id}-${i}`,
    })),
    humanAccepted,
    leakageReason,
    labeler: "fixture-generator",
  };
}

// ─── 60 个跨领域样本 ──────────────────────────────────────────────────────

export const QUESTION_RUBRIC_GOLD: QuestionRubricGoldSample[] = [
  // ─── distributed-systems (6) ────────────────────────────────────────────
  makeSample("qr-001", "distributed-systems",
    "CAP 定理指出分布式系统不能同时满足一致性、可用性和分区容错性",
    "In a distributed system, you can only pick two out of consistency, availability, and partition tolerance",
    "explain",
    "请解释 CAP 定理中一致性、可用性和分区容错性的含义，以及为什么不能同时满足三者。",
    [
      { key: "cap-c", criterion: "解释一致性(Consistency)的含义", expectedConcept: "所有节点同时看到相同数据", weight: 2, required: true },
      { key: "cap-a", criterion: "解释可用性(Availability)的含义", expectedConcept: "每个请求都能收到非错误响应", weight: 2, required: true },
      { key: "cap-p", criterion: "解释分区容错性(Partition Tolerance)的含义", expectedConcept: "系统在网络分区时继续运作", weight: 2, required: true },
      { key: "cap-tradeoff", criterion: "解释为什么不能同时满足三者", expectedConcept: "网络分区时必须在C和A之间选择", weight: 3, required: true },
    ],
  ),
  makeSample("qr-002", "distributed-systems",
    "最终一致性是指在没有新写入的情况下，所有副本最终会收敛到相同值",
    "Eventually, all replicas will converge to the same value if no new writes occur",
    "explain",
    "什么是最终一致性？它与强一致性有何区别？",
    [
      { key: "ec-def", criterion: "定义最终一致性", expectedConcept: "副本最终收敛到相同值", weight: 2, required: true },
      { key: "ec-vs-strong", criterion: "对比最终一致性与强一致性", expectedConcept: "强一致性要求立即可见", weight: 2, required: true },
    ],
  ),
  makeSample("qr-003", "distributed-systems",
    "Raft 共识算法通过 Leader 选举和日志复制实现容错",
    "Raft achieves consensus through leader election and log replication",
    "apply",
    "给定一个 5 节点 Raft 集群，如果 Leader 节点宕机，请描述选举新 Leader 的过程。",
    [
      { key: "raft-leader", criterion: "描述 Leader 选举过程", expectedConcept: "Follower 超时后变为 Candidate 并请求投票", weight: 2, required: true },
      { key: "raft-term", criterion: "解释 term 的作用", expectedConcept: "term 是逻辑时钟防止过期 Leader", weight: 2, required: true },
      { key: "raft-quorum", criterion: "说明多数派投票要求", expectedConcept: "需获得多数节点投票", weight: 3, required: true },
    ],
  ),
  makeSample("qr-004", "distributed-systems",
    "两阶段提交协议包含协调者和参与者，通过 prepare 和 commit 两个阶段保证原子性",
    "Two-phase commit has a coordinator and participants, using prepare and commit phases",
    "explain",
    "请解释两阶段提交协议的工作原理及其主要缺点。",
    [
      { key: "2pc-prepare", criterion: "解释 prepare 阶段", expectedConcept: "协调者询问参与者是否可以提交", weight: 2, required: true },
      { key: "2pc-commit", criterion: "解释 commit 阶段", expectedConcept: "所有参与者同意后协调者发送提交", weight: 2, required: true },
      { key: "2pc-blocking", criterion: "指出主要缺点", expectedConcept: "协调者宕机导致阻塞", weight: 3, required: true },
    ],
  ),
  makeSample("qr-005", "distributed-systems",
    "Gossip 协议通过节点间随机通信传播信息，具有高可扩展性",
    "Gossip protocols spread information through random pairwise communication",
    "example",
    "请举一个使用 Gossip 协议的实际系统例子，并解释其传播过程。",
    [
      { key: "gossip-example", criterion: "给出实际系统例子", expectedConcept: "Cassandra/DynamoDB 使用 Gossip", weight: 2, required: true },
      { key: "gossip-process", criterion: "解释传播过程", expectedConcept: "每个节点随机选peer交换状态", weight: 2, required: true },
    ],
  ),
  makeSample("qr-006", "distributed-systems",
    "向量时钟通过为每个节点维护一个逻辑时钟数组来捕获因果关系",
    "Vector clocks capture causality by maintaining an array of logical clocks per node",
    "explain",
    "请解释向量时钟的工作原理，以及它如何解决 Lamport 时钟无法区分并发事件的问题。",
    [
      { key: "vc-structure", criterion: "描述向量时钟结构", expectedConcept: "每个节点维护一个数组", weight: 2, required: true },
      { key: "vc-causality", criterion: "解释因果关系判定", expectedConcept: "比较向量大小判定 happened-before", weight: 3, required: true },
      { key: "vc-concurrent", criterion: "说明并发事件检测", expectedConcept: "向量不可比较时为并发", weight: 2, required: true },
    ],
  ),

  // ─── data-structures (6) ────────────────────────────────────────────────
  makeSample("qr-007", "data-structures",
    "红黑树是一种自平衡二叉搜索树，保证最长路径不超过最短路径的两倍",
    "Red-black tree is a self-balancing BST where the longest path is at most twice the shortest",
    "explain",
    "请解释红黑树的五个性质，以及它们如何保证树的平衡性。",
    [
      { key: "rb-color", criterion: "描述节点着色规则", expectedConcept: "节点为红或黑，根为黑", weight: 1, required: true },
      { key: "rb-nil", criterion: "描述 nil 节点规则", expectedConcept: "叶子(nil)为黑", weight: 1, required: false },
      { key: "rb-red", criterion: "描述红色节点约束", expectedConcept: "红节点的子节点为黑", weight: 2, required: true },
      { key: "rb-height", criterion: "解释黑高平衡性", expectedConcept: "任一节点到叶子的黑节点数相同", weight: 3, required: true },
    ],
  ),
  makeSample("qr-008", "data-structures",
    "B+ 树的所有值都存储在叶子节点，内部节点只存储索引键",
    "In a B+ tree, all values are stored in leaf nodes; internal nodes only store index keys",
    "explain",
    "请解释 B+ 树的结构特点，以及它为什么适合作为数据库索引。",
    [
      { key: "bp-leaf", criterion: "解释叶子节点存储值", expectedConcept: "所有数据在叶子", weight: 2, required: true },
      { key: "bp-internal", criterion: "解释内部节点只存键", expectedConcept: "内部节点只存索引", weight: 2, required: true },
      { key: "bp-range", criterion: "说明范围查询优势", expectedConcept: "叶子节点链表连接", weight: 2, required: true },
    ],
  ),
  makeSample("qr-009", "data-structures",
    "跳表通过多级链表实现 O(log n) 的查找、插入和删除",
    "Skip lists achieve O(log n) operations through multi-level linked lists",
    "apply",
    "给定一个跳表，请描述查找元素 42 的过程。",
    [
      { key: "sl-levels", criterion: "描述多级链表结构", expectedConcept: "从最高层开始查找", weight: 2, required: true },
      { key: "sl-search", criterion: "描述查找下降过程", expectedConcept: "在当前层向右到适当位置后下降", weight: 2, required: true },
    ],
  ),
  makeSample("qr-010", "data-structures",
    "一致性哈希通过虚拟环和虚拟节点解决数据分布不均的问题",
    "Consistent hashing uses a virtual ring and virtual nodes to solve uneven distribution",
    "explain",
    "请解释一致性哈希的工作原理，以及虚拟节点的作用。",
    [
      { key: "ch-ring", criterion: "描述哈希环结构", expectedConcept: "节点和键映射到0-2^32环上", weight: 2, required: true },
      { key: "ch-lookup", criterion: "解释查找过程", expectedConcept: "顺时针找到第一个节点", weight: 2, required: true },
      { key: "ch-virtual", criterion: "解释虚拟节点作用", expectedConcept: "增加节点数量使分布均匀", weight: 3, required: true },
    ],
  ),
  makeSample("qr-011", "data-structures",
    "Trie 树通过共享前缀来压缩存储空间，常用于字符串检索",
    "Trie trees compress storage by sharing prefixes, useful for string retrieval",
    "example",
    "请举一个 Trie 树的实际应用例子，并说明其查找过程。",
    [
      { key: "trie-app", criterion: "给出实际应用", expectedConcept: "自动补全/拼写检查/IP路由", weight: 2, required: true },
      { key: "trie-search", criterion: "说明查找过程", expectedConcept: "逐字符匹配前缀", weight: 2, required: true },
    ],
  ),
  makeSample("qr-012", "data-structures",
    "布隆过滤器使用多个哈希函数和位数组实现空间高效的集合成员检测",
    "Bloom filters use multiple hash functions and a bit array for space-efficient membership testing",
    "explain",
    "请解释布隆过滤器的工作原理及其假阳性问题。",
    [
      { key: "bf-structure", criterion: "描述位数组和哈希结构", expectedConcept: "k个哈希函数映射到位数组", weight: 2, required: true },
      { key: "bf-false-pos", criterion: "解释假阳性原因", expectedConcept: "不同元素的哈希位重叠", weight: 3, required: true },
      { key: "bf-no-false-neg", criterion: "说明无假阴性", expectedConcept: "元素一定被设置过", weight: 2, required: true },
    ],
  ),

  // ─── machine-learning (6) ──────────────────────────────────────────────
  makeSample("qr-013", "machine-learning",
    "梯度下降通过沿损失函数负梯度方向迭代更新参数来最小化损失",
    "Gradient descent minimizes loss by iteratively updating parameters along the negative gradient",
    "explain",
    "请解释梯度下降的工作原理，并说明学习率对收敛的影响。",
    [
      { key: "gd-gradient", criterion: "解释梯度的含义", expectedConcept: "损失函数对参数的偏导数", weight: 2, required: true },
      { key: "gd-update", criterion: "描述参数更新公式", expectedConcept: "参数 = 参数 - 学习率 * 梯度", weight: 3, required: true },
      { key: "gd-lr", criterion: "说明学习率影响", expectedConcept: "过大不收敛，过小收敛慢", weight: 2, required: true },
    ],
  ),
  makeSample("qr-014", "machine-learning",
    "过拟合是指模型在训练数据上表现好但在新数据上表现差",
    "Overfitting occurs when a model performs well on training data but poorly on new data",
    "explain",
    "请解释过拟合的原因和至少两种防止过拟合的方法。",
    [
      { key: "of-cause", criterion: "解释过拟合原因", expectedConcept: "模型复杂度过高/训练数据不足", weight: 2, required: true },
      { key: "of-prevent1", criterion: "描述一种防止方法", expectedConcept: "正则化/Dropout/早停", weight: 2, required: true },
      { key: "of-prevent2", criterion: "描述另一种防止方法", expectedConcept: "数据增强/交叉验证", weight: 2, required: true },
    ],
  ),
  makeSample("qr-015", "machine-learning",
    "交叉验证通过将数据分为多个子集来评估模型泛化能力",
    "Cross-validation evaluates model generalization by splitting data into multiple subsets",
    "apply",
    "给定一个 10 折交叉验证场景，请描述每一轮的训练和验证过程。",
    [
      { key: "cv-split", criterion: "描述数据分割", expectedConcept: "数据分为10份", weight: 2, required: true },
      { key: "cv-iter", criterion: "描述迭代过程", expectedConcept: "每次用9份训练1份验证", weight: 2, required: true },
      { key: "cv-avg", criterion: "说明最终评估", expectedConcept: "10次结果取平均", weight: 2, required: true },
    ],
  ),
  makeSample("qr-016", "machine-learning",
    "Softmax 函数将向量转换为概率分布，使所有元素之和为 1",
    "Softmax converts a vector into a probability distribution summing to 1",
    "explain",
    "请解释 Softmax 函数的数学定义及其在多分类问题中的应用。",
    [
      { key: "sm-formula", criterion: "写出 Softmax 公式", expectedConcept: "exp(xi) / sum(exp(xj))", weight: 3, required: true },
      { key: "sm-prob", criterion: "解释概率分布性质", expectedConcept: "输出非负且和为1", weight: 2, required: true },
      { key: "sm-classify", criterion: "说明多分类应用", expectedConcept: "取最大概率类别为预测", weight: 2, required: true },
    ],
  ),
  makeSample("qr-017", "machine-learning",
    "反向传播算法通过链式法则计算损失函数对网络参数的梯度",
    "Backpropagation computes gradients using the chain rule",
    "explain",
    "请解释反向传播算法的核心思想和工作流程。",
    [
      { key: "bp-forward", criterion: "描述前向传播", expectedConcept: "输入逐层计算输出", weight: 2, required: true },
      { key: "bp-chain", criterion: "解释链式法则", expectedConcept: "逐层计算偏导数", weight: 3, required: true },
      { key: "bp-backward", criterion: "描述反向计算梯度", expectedConcept: "从输出层向输入层传播", weight: 2, required: true },
    ],
  ),
  makeSample("qr-018", "machine-learning",
    "L1 正则化通过添加参数绝对值之和的惩罚项促进稀疏性",
    "L1 regularization adds the sum of absolute values as a penalty, promoting sparsity",
    "explain",
    "请解释 L1 正则化为什么能产生稀疏解，并与 L2 正则化对比。",
    [
      { key: "l1-penalty", criterion: "描述 L1 惩罚项", expectedConcept: "lambda * sum(|w|)", weight: 2, required: true },
      { key: "l1-sparse", criterion: "解释稀疏性原因", expectedConcept: "绝对值在0处不可导，倾向于置零", weight: 3, required: true },
      { key: "l1-vs-l2", criterion: "对比 L1 和 L2", expectedConcept: "L2 产生小值但不为零", weight: 2, required: true },
    ],
  ),

  // ─── web-security (6) ──────────────────────────────────────────────────
  makeSample("qr-019", "web-security",
    "SQL 注入通过在输入中嵌入恶意 SQL 片段来操纵数据库查询",
    "SQL injection manipulates database queries by embedding malicious SQL in input",
    "apply",
    "给定一个登录表单 `SELECT * FROM users WHERE name = '$input'`，请展示一种 SQL 注入方式及其防御方法。",
    [
      { key: "sqli-example", criterion: "展示注入方式", expectedConcept: "输入 ' OR '1'='1 绕过验证", weight: 3, required: true },
      { key: "sqli-defend", criterion: "描述防御方法", expectedConcept: "参数化查询/预编译语句", weight: 2, required: true },
    ],
  ),
  makeSample("qr-020", "web-security",
    "XSS 攻击通过在网页中注入恶意脚本来窃取用户信息或劫持会话",
    "XSS attacks inject malicious scripts into web pages to steal user data",
    "explain",
    "请解释存储型 XSS 和反射型 XSS 的区别，以及各自的防御方法。",
    [
      { key: "xss-stored", criterion: "解释存储型 XSS", expectedConcept: "恶意脚本存储在服务器数据库", weight: 2, required: true },
      { key: "xss-reflected", criterion: "解释反射型 XSS", expectedConcept: "恶意脚本在URL中即时反射", weight: 2, required: true },
      { key: "xss-defend", criterion: "描述防御方法", expectedConcept: "输出编码/CSP/HttpOnly Cookie", weight: 2, required: true },
    ],
  ),
  makeSample("qr-021", "web-security",
    "CSRF 攻击利用用户已认证的身份在用户不知情的情况下发送请求",
    "CSRF exploits a user's authenticated session to send requests without consent",
    "explain",
    "请解释 CSRF 攻击的工作原理和至少两种防御方法。",
    [
      { key: "csrf-principle", criterion: "解释 CSRF 原理", expectedConcept: "利用浏览器自动携带Cookie", weight: 2, required: true },
      { key: "csrf-token", criterion: "描述 Token 防御", expectedConcept: "服务器生成唯一Token验证", weight: 2, required: true },
      { key: "csrf-samesite", criterion: "描述 SameSite 防御", expectedConcept: "Cookie的SameSite属性", weight: 2, required: true },
    ],
  ),
  makeSample("qr-022", "web-security",
    "JWT 由 Header、Payload 和 Signature 三部分组成，用于无状态认证",
    "JWT consists of Header, Payload, and Signature for stateless authentication",
    "explain",
    "请解释 JWT 的结构组成以及它在无状态认证中的工作原理。",
    [
      { key: "jwt-header", criterion: "描述 Header", expectedConcept: "包含算法和类型", weight: 1, required: true },
      { key: "jwt-payload", criterion: "描述 Payload", expectedConcept: "包含声明(claims)", weight: 2, required: true },
      { key: "jwt-sig", criterion: "解释 Signature", expectedConcept: "用密钥签名防止篡改", weight: 3, required: true },
    ],
  ),
  makeSample("qr-023", "web-security",
    "HTTPS 通过 TLS/SSL 协议在 HTTP 基础上提供加密、认证和完整性保护",
    "HTTPS provides encryption, authentication, and integrity through TLS/SSL",
    "apply",
    "给定一个浏览器访问 https://example.com 的场景，请描述 TLS 握手过程。",
    [
      { key: "tls-hello", criterion: "描述 ClientHello", expectedConcept: "客户端发送支持的加密套件", weight: 2, required: true },
      { key: "tls-cert", criterion: "描述证书验证", expectedConcept: "服务器发送证书，客户端验证", weight: 3, required: true },
      { key: "tls-key", criterion: "描述密钥交换", expectedConcept: "协商会话密钥", weight: 2, required: true },
    ],
  ),
  makeSample("qr-024", "web-security",
    "CSP 通过限制资源加载来源来防止 XSS 和数据注入攻击",
    "CSP prevents XSS by restricting resource loading sources",
    "explain",
    "请解释 Content Security Policy 的工作原理及其主要指令。",
    [
      { key: "csp-principle", criterion: "解释 CSP 原理", expectedConcept: "白名单限制可执行脚本来源", weight: 2, required: true },
      { key: "csp-directive", criterion: "描述主要指令", expectedConcept: "script-src/img-src/default-src", weight: 2, required: true },
      { key: "csp-nonce", criterion: "解释 nonce 机制", expectedConcept: "为内联脚本生成一次性令牌", weight: 2, required: false },
    ],
  ),

  // ─── database-design (6) ───────────────────────────────────────────────
  makeSample("qr-025", "database-design",
    "第三范式(3NF)要求非主属性既不传递依赖于主键也不部分依赖于主键",
    "3NF requires non-key attributes to be non-transitively and non-partially dependent on the primary key",
    "explain",
    "请解释第三范式的定义，并举一个违反 3NF 的例子。",
    [
      { key: "3nf-def", criterion: "定义 3NF", expectedConcept: "消除传递依赖", weight: 3, required: true },
      { key: "3nf-violation", criterion: "举例违反 3NF", expectedConcept: "如学生表含系名和系主任", weight: 2, required: true },
      { key: "3nf-fix", criterion: "描述如何修复", expectedConcept: "分解为两个表", weight: 2, required: true },
    ],
  ),
  makeSample("qr-026", "database-design",
    "MVCC 通过维护数据的多个版本实现读写不互相阻塞",
    "MVCC enables non-blocking reads by maintaining multiple versions of data",
    "explain",
    "请解释 MVCC 的工作原理及其如何解决读写冲突。",
    [
      { key: "mvcc-version", criterion: "描述版本链", expectedConcept: "每行保存多个版本", weight: 2, required: true },
      { key: "mvcc-snapshot", criterion: "解释快照读", expectedConcept: "读操作看到一致性快照", weight: 2, required: true },
      { key: "mvcc-conflict", criterion: "说明读写不阻塞", expectedConcept: "读旧版本写新版本", weight: 3, required: true },
    ],
  ),
  makeSample("qr-027", "database-design",
    "数据库索引使用 B+ 树结构加速查询，但增加写入开销",
    "Database indexes use B+ trees to speed up queries at the cost of write overhead",
    "apply",
    "给定一个用户表 `users(id, email, created_at)`，请说明如何为 `email` 创建索引以及索引的利弊。",
    [
      { key: "idx-create", criterion: "描述创建索引", expectedConcept: "CREATE INDEX ON users(email)", weight: 2, required: true },
      { key: "idx-benefit", criterion: "说明查询加速", expectedConcept: "等值查询和范围查询变快", weight: 2, required: true },
      { key: "idx-cost", criterion: "说明写入代价", expectedConcept: "插入/更新需维护索引", weight: 2, required: true },
    ],
  ),
  makeSample("qr-028", "database-design",
    "事务的 ACID 性质包括原子性、一致性、隔离性和持久性",
    "ACID properties are Atomicity, Consistency, Isolation, and Durability",
    "explain",
    "请分别解释事务的 ACID 四个性质，并各举一个例子。",
    [
      { key: "acid-a", criterion: "解释原子性", expectedConcept: "事务全做或全不做", weight: 2, required: true },
      { key: "acid-c", criterion: "解释一致性", expectedConcept: "事务前后数据一致", weight: 2, required: true },
      { key: "acid-i", criterion: "解释隔离性", expectedConcept: "并发事务互不干扰", weight: 2, required: true },
      { key: "acid-d", criterion: "解释持久性", expectedConcept: "提交后永久保存", weight: 2, required: true },
    ],
  ),
  makeSample("qr-029", "database-design",
    "数据库分片通过水平拆分将大表分散到多个节点提高可扩展性",
    "Database sharding improves scalability by horizontally splitting large tables",
    "explain",
    "请解释数据库分片的基本策略（范围分片、哈希分片）及其优缺点。",
    [
      { key: "shard-range", criterion: "解释范围分片", expectedConcept: "按键值范围分配", weight: 2, required: true },
      { key: "shard-hash", criterion: "解释哈希分片", expectedConcept: "按哈希值均匀分配", weight: 2, required: true },
      { key: "shard-tradeoff", criterion: "说明优缺点", expectedConcept: "提高吞吐但跨分片查询难", weight: 3, required: true },
    ],
  ),
  makeSample("qr-030", "database-design",
    "乐观锁通过版本号检测并发冲突，适用于读多写少场景",
    "Optimistic locking uses version numbers to detect conflicts, suitable for read-heavy workloads",
    "apply",
    "给定一个库存表 `inventory(id, count, version)`，请描述使用乐观锁更新库存的过程。",
    [
      { key: "ol-read", criterion: "描述读取版本号", expectedConcept: "先读取当前version", weight: 2, required: true },
      { key: "ol-update", criterion: "描述条件更新", expectedConcept: "WHERE version = 旧version", weight: 3, required: true },
      { key: "ol-retry", criterion: "说明冲突处理", expectedConcept: "更新0行时重试", weight: 2, required: true },
    ],
  ),

  // ─── network-protocols (6) ──────────────────────────────────────────────
  makeSample("qr-031", "network-protocols",
    "TCP 三次握手通过 SYN、SYN-ACK、ACK 建立可靠连接",
    "TCP establishes connections via SYN, SYN-ACK, ACK three-way handshake",
    "explain",
    "请解释 TCP 三次握手的过程，以及为什么需要三次而不是两次。",
    [
      { key: "tcp-syn", criterion: "描述 SYN", expectedConcept: "客户端发送SYN到服务器", weight: 2, required: true },
      { key: "tcp-synack", criterion: "描述 SYN-ACK", expectedConcept: "服务器回SYN+ACK", weight: 2, required: true },
      { key: "tcp-ack", criterion: "描述 ACK", expectedConcept: "客户端回ACK确认", weight: 2, required: true },
      { key: "tcp-why3", criterion: "解释为何需要三次", expectedConcept: "防止旧连接请求到达", weight: 3, required: true },
    ],
  ),
  makeSample("qr-032", "network-protocols",
    "HTTP/2 通过多路复用、头部压缩和服务器推送提高性能",
    "HTTP/2 improves performance through multiplexing, header compression, and server push",
    "explain",
    "请解释 HTTP/2 相比 HTTP/1.1 的三个主要改进。",
    [
      { key: "h2-mux", criterion: "解释多路复用", expectedConcept: "一个连接多个流", weight: 2, required: true },
      { key: "h2-hpack", criterion: "解释头部压缩", expectedConcept: "HPACK压缩重复头部", weight: 2, required: true },
      { key: "h2-push", criterion: "解释服务器推送", expectedConcept: "主动推送资源", weight: 2, required: false },
    ],
  ),
  makeSample("qr-033", "network-protocols",
    "DNS 使用分层分布式数据库将域名解析为 IP 地址",
    "DNS resolves domain names to IP addresses using a hierarchical distributed database",
    "apply",
    "当用户在浏览器输入 www.example.com 时，请描述 DNS 解析的完整过程。",
    [
      { key: "dns-cache", criterion: "描述本地缓存检查", expectedConcept: "先查浏览器和OS缓存", weight: 1, required: true },
      { key: "dns-recursive", criterion: "描述递归查询", expectedConcept: "本地DNS服务器递归查询", weight: 2, required: true },
      { key: "dns-iterative", criterion: "描述迭代查询", expectedConcept: "根→顶级域→权威", weight: 3, required: true },
    ],
  ),
  makeSample("qr-034", "network-protocols",
    "TLS 1.3 将握手从 2-RTT 减少到 1-RTT，支持 0-RTT 恢复",
    "TLS 1.3 reduces handshake to 1-RTT and supports 0-RTT resumption",
    "explain",
    "请解释 TLS 1.3 相比 TLS 1.2 在握手方面的改进。",
    [
      { key: "tls13-1rtt", criterion: "解释 1-RTT 握手", expectedConcept: "合并握手消息", weight: 2, required: true },
      { key: "tls13-0rtt", criterion: "解释 0-RTT 恢复", expectedConcept: "复用之前会话密钥", weight: 2, required: true },
      { key: "tls13-security", criterion: "说明安全改进", expectedConcept: "移除不安全算法", weight: 2, required: false },
    ],
  ),
  makeSample("qr-035", "network-protocols",
    "WebSocket 提供全双工通信，允许服务器主动推送消息",
    "WebSocket provides full-duplex communication, allowing server push",
    "apply",
    "请描述从 HTTP 升级到 WebSocket 连接的过程。",
    [
      { key: "ws-upgrade", criterion: "描述升级请求", expectedConcept: "HTTP Upgrade: websocket", weight: 2, required: true },
      { key: "ws-handshake", criterion: "描述握手响应", expectedConcept: "101 Switching Protocols", weight: 2, required: true },
      { key: "ws-full-duplex", criterion: "说明全双工通信", expectedConcept: "建立后双向发送帧", weight: 2, required: true },
    ],
  ),
  makeSample("qr-036", "network-protocols",
    "CDN 通过边缘缓存和就近分发降低延迟和源站负载",
    "CDN reduces latency and origin load through edge caching and proximity distribution",
    "explain",
    "请解释 CDN 的工作原理及其缓存刷新策略。",
    [
      { key: "cdn-edge", criterion: "解释边缘节点", expectedConcept: "内容缓存在全球节点", weight: 2, required: true },
      { key: "cdn-routing", criterion: "解释就近路由", expectedConcept: "DNS解析到最近节点", weight: 2, required: true },
      { key: "cdn-refresh", criterion: "说明缓存策略", expectedConcept: "TTL/主动推送/版本化", weight: 2, required: false },
    ],
  ),

  // ─── software-architecture (6) ──────────────────────────────────────────
  makeSample("qr-037", "software-architecture",
    "依赖注入通过将依赖从组件内部移到外部传入来实现控制反转",
    "Dependency injection achieves IoC by passing dependencies from outside",
    "explain",
    "请解释依赖注入的核心思想和三种注入方式（构造器、Setter、接口）。",
    [
      { key: "di-principle", criterion: "解释控制反转", expectedConcept: "依赖由外部容器提供", weight: 2, required: true },
      { key: "di-constructor", criterion: "描述构造器注入", expectedConcept: "通过构造函数传入", weight: 2, required: true },
      { key: "di-benefit", criterion: "说明解耦好处", expectedConcept: "便于测试和替换", weight: 2, required: true },
    ],
  ),
  makeSample("qr-038", "software-architecture",
    "微服务架构将单体应用拆分为独立部署的小服务",
    "Microservices split monoliths into independently deployable small services",
    "explain",
    "请解释微服务架构的优缺点，以及服务发现的作用。",
    [
      { key: "ms-pro", criterion: "说明优点", expectedConcept: "独立部署/技术异构/可扩展", weight: 2, required: true },
      { key: "ms-con", criterion: "说明缺点", expectedConcept: "分布式复杂性/数据一致性", weight: 2, required: true },
      { key: "ms-discovery", criterion: "解释服务发现", expectedConcept: "服务注册和查找", weight: 2, required: true },
    ],
  ),
  makeSample("qr-039", "software-architecture",
    "CQRS 将读操作和写操作分离到不同的模型中",
    "CQRS separates read and write operations into different models",
    "apply",
    "给定一个电商系统，请描述如何使用 CQRS 分离商品查询和订单创建。",
    [
      { key: "cqrs-read", criterion: "描述读模型", expectedConcept: "优化的查询视图", weight: 2, required: true },
      { key: "cqrs-write", criterion: "描述写模型", expectedConcept: "命令处理和领域模型", weight: 2, required: true },
      { key: "cqrs-sync", criterion: "说明同步机制", expectedConcept: "事件驱动更新读模型", weight: 3, required: true },
    ],
  ),
  makeSample("qr-040", "software-architecture",
    "事件驱动架构通过异步事件消息实现服务间松耦合",
    "Event-driven architecture achieves loose coupling through async event messages",
    "explain",
    "请解释事件驱动架构的核心组件和至少两个优势。",
    [
      { key: "eda-producer", criterion: "描述事件生产者", expectedConcept: "发布事件到消息总线", weight: 2, required: true },
      { key: "eda-consumer", criterion: "描述事件消费者", expectedConcept: "订阅并处理事件", weight: 2, required: true },
      { key: "eda-benefit", criterion: "说明优势", expectedConcept: "解耦/可扩展/弹性", weight: 2, required: true },
    ],
  ),
  makeSample("qr-041", "software-architecture",
    "限界上下文(Bounded Context)是领域驱动设计中的核心概念，定义了模型的适用边界",
    "Bounded Context defines the boundary within which a domain model is applicable",
    "explain",
    "请解释限界上下文的概念及其在微服务拆分中的作用。",
    [
      { key: "bc-def", criterion: "定义限界上下文", expectedConcept: "模型的一致性边界", weight: 2, required: true },
      { key: "bc-ms", criterion: "说明与微服务关系", expectedConcept: "一个上下文对应一个服务", weight: 3, required: true },
      { key: "bc-context-map", criterion: "描述上下文映射", expectedConcept: "定义上下文间关系", weight: 2, required: false },
    ],
  ),
  makeSample("qr-042", "software-architecture",
    "Saga 模式通过一系列本地事务和补偿操作管理分布式事务",
    "Saga manages distributed transactions through local transactions and compensations",
    "explain",
    "请解释 Saga 模式的工作原理，并区分编排式和协同式两种实现方式。",
    [
      { key: "saga-local", criterion: "解释本地事务", expectedConcept: "每步是独立本地事务", weight: 2, required: true },
      { key: "saga-compensate", criterion: "解释补偿操作", expectedConcept: "失败时执行逆向操作", weight: 3, required: true },
      { key: "saga-types", criterion: "区分两种实现", expectedConcept: "编排(集中)vs协同(事件)", weight: 2, required: true },
    ],
  ),

  // ─── concurrency (6) ───────────────────────────────────────────────────
  makeSample("qr-043", "concurrency",
    "互斥锁保证同一时间只有一个线程访问共享资源",
    "Mutex ensures only one thread accesses a shared resource at a time",
    "explain",
    "请解释互斥锁的工作原理，并说明死锁产生的四个必要条件。",
    [
      { key: "mutex-principle", criterion: "解释互斥原理", expectedConcept: "加锁/解锁保证独占", weight: 2, required: true },
      { key: "deadlock-4", criterion: "列出死锁四条件", expectedConcept: "互斥/占有等待/不可剥夺/循环等待", weight: 3, required: true },
    ],
  ),
  makeSample("qr-044", "concurrency",
    "CAS(Compare-And-Swap)是无锁编程的核心原语，通过原子比较和交换实现并发安全",
    "CAS enables lock-free programming through atomic compare and swap",
    "explain",
    "请解释 CAS 的工作原理及其 ABA 问题。",
    [
      { key: "cas-principle", criterion: "解释 CAS 原理", expectedConcept: "比较预期值后原子更新", weight: 3, required: true },
      { key: "cas-aba", criterion: "解释 ABA 问题", expectedConcept: "值从A变B又变A", weight: 2, required: true },
      { key: "cas-fix", criterion: "描述 ABA 解决", expectedConcept: "版本号/标记位", weight: 2, required: false },
    ],
  ),
  makeSample("qr-045", "concurrency",
    "读写锁允许多个读者同时访问但写者独占",
    "Read-write lock allows concurrent reads but exclusive writes",
    "apply",
    "给定一个多线程缓存场景（读多写少），请描述如何使用读写锁优化性能。",
    [
      { key: "rwlock-read", criterion: "描述读锁共享", expectedConcept: "多个读线程可同时持有", weight: 2, required: true },
      { key: "rwlock-write", criterion: "描述写锁独占", expectedConcept: "写线程独占锁", weight: 2, required: true },
      { key: "rwlock-scene", criterion: "说明适用场景", expectedConcept: "读多写少时性能优", weight: 2, required: true },
    ],
  ),
  makeSample("qr-046", "concurrency",
    "Channel 是 Go 语言中用于 goroutine 间通信的管道",
    "Channels are pipes for goroutine communication in Go",
    "explain",
    "请解释 Go 语言 Channel 的工作原理，并说明有缓冲和无缓冲 Channel 的区别。",
    [
      { key: "ch-unbuffered", criterion: "解释无缓冲 Channel", expectedConcept: "发送和接收同步", weight: 2, required: true },
      { key: "ch-buffered", criterion: "解释有缓冲 Channel", expectedConcept: "缓冲未满时异步", weight: 2, required: true },
      { key: "ch-select", criterion: "描述 select 语句", expectedConcept: "多路复用等待Channel", weight: 2, required: false },
    ],
  ),
  makeSample("qr-047", "concurrency",
    "线程池通过预创建和复用线程减少创建销毁开销",
    "Thread pools reduce creation/destruction overhead by pre-creating and reusing threads",
    "explain",
    "请解释线程池的工作原理和核心参数。",
    [
      { key: "tp-core", criterion: "解释核心线程数", expectedConcept: "常驻线程", weight: 2, required: true },
      { key: "tp-queue", criterion: "解释任务队列", expectedConcept: "超出核心线程的任务排队", weight: 2, required: true },
      { key: "tp-reject", criterion: "解释拒绝策略", expectedConcept: "队列满时的处理", weight: 2, required: true },
    ],
  ),
  makeSample("qr-048", "concurrency",
    "内存屏障(Memory Barrier)通过限制指令重排序保证可见性和有序性",
    "Memory barriers prevent instruction reordering to ensure visibility and ordering",
    "explain",
    "请解释内存屏障的作用，并说明 happens-before 关系。",
    [
      { key: "mb-visibility", criterion: "解释可见性保证", expectedConcept: "强制刷新CPU缓存", weight: 2, required: true },
      { key: "mb-ordering", criterion: "解释有序性保证", expectedConcept: "禁止指令重排", weight: 3, required: true },
      { key: "mb-hb", criterion: "解释 happens-before", expectedConcept: "前操作的结果对后操作可见", weight: 2, required: true },
    ],
  ),

  // ─── cloud-computing (6) ────────────────────────────────────────────────
  makeSample("qr-049", "cloud-computing",
    "容器化通过 Linux Namespace 和 Cgroups 实现进程级隔离",
    "Containerization uses Linux Namespace and Cgroups for process isolation",
    "explain",
    "请解释容器化的底层技术原理（Namespace 和 Cgroups）。",
    [
      { key: "container-ns", criterion: "解释 Namespace", expectedConcept: "隔离进程视图(网络/PID/文件系统)", weight: 3, required: true },
      { key: "container-cg", criterion: "解释 Cgroups", expectedConcept: "限制资源使用(CPU/内存)", weight: 2, required: true },
      { key: "container-vs-vm", criterion: "对比容器和虚拟机", expectedConcept: "容器共享内核更轻量", weight: 2, required: true },
    ],
  ),
  makeSample("qr-050", "cloud-computing",
    "Kubernetes 通过 Pod、Deployment、Service 等资源管理容器化应用",
    "Kubernetes manages containerized apps through Pods, Deployments, and Services",
    "explain",
    "请解释 Kubernetes 中 Pod、Deployment 和 Service 的概念及其关系。",
    [
      { key: "k8s-pod", criterion: "解释 Pod", expectedConcept: "最小调度单位含一个或多个容器", weight: 2, required: true },
      { key: "k8s-deploy", criterion: "解释 Deployment", expectedConcept: "管理Pod副本和滚动更新", weight: 2, required: true },
      { key: "k8s-svc", criterion: "解释 Service", expectedConcept: "提供稳定网络访问和负载均衡", weight: 2, required: true },
    ],
  ),
  makeSample("qr-051", "cloud-computing",
    "服务网格(Service Mesh)通过 Sidecar 代理实现流量管理和可观测性",
    "Service Mesh uses sidecar proxies for traffic management and observability",
    "explain",
    "请解释 Service Mesh 的工作原理及其与微服务的关系。",
    [
      { key: "mesh-sidecar", criterion: "解释 Sidecar 模式", expectedConcept: "每个Pod旁挂代理容器", weight: 2, required: true },
      { key: "mesh-traffic", criterion: "解释流量管理", expectedConcept: "代理拦截所有进出流量", weight: 3, required: true },
      { key: "mesh-obs", criterion: "解释可观测性", expectedConcept: "自动收集指标/链路/日志", weight: 2, required: true },
    ],
  ),
  makeSample("qr-052", "cloud-computing",
    "IaC(Infrastructure as Code)通过代码定义和管理基础设施",
    "IaC manages infrastructure through code definitions",
    "apply",
    "给定一个需要部署 3 个微服务到 Kubernetes 的场景，请描述使用 IaC 的流程。",
    [
      { key: "iac-define", criterion: "描述基础设施定义", expectedConcept: "用YAML/HCL定义资源", weight: 2, required: true },
      { key: "iac-apply", criterion: "描述部署流程", expectedConcept: "plan→apply→verify", weight: 2, required: true },
      { key: "iac-version", criterion: "说明版本管理", expectedConcept: "代码仓库管理变更历史", weight: 2, required: true },
    ],
  ),
  makeSample("qr-053", "cloud-computing",
    "蓝绿部署通过维护两套相同环境实现零停机发布",
    "Blue-green deployment achieves zero-downtime releases with two identical environments",
    "explain",
    "请解释蓝绿部署的工作原理及其与金丝雀发布的区别。",
    [
      { key: "bg-principle", criterion: "解释蓝绿原理", expectedConcept: "蓝绿两套环境切换", weight: 2, required: true },
      { key: "bg-vs-canary", criterion: "对比金丝雀", expectedConcept: "蓝绿全量切换/金丝雀渐进", weight: 3, required: true },
    ],
  ),
  makeSample("qr-054", "cloud-computing",
    "Serverless 架构让开发者无需管理服务器，按需执行代码",
    "Serverless architecture executes code on-demand without server management",
    "explain",
    "请解释 Serverless 的核心概念（FaaS 和 BaaS）及其适用场景。",
    [
      { key: "sl-faas", criterion: "解释 FaaS", expectedConcept: "函数即服务/事件触发执行", weight: 2, required: true },
      { key: "sl-baas", criterion: "解释 BaaS", expectedConcept: "后端即服务/托管数据库存储", weight: 2, required: true },
      { key: "sl-scene", criterion: "说明适用场景", expectedConcept: "事件驱动/突发流量/短任务", weight: 2, required: true },
    ],
  ),

  // ─── testing-qa (6) ─────────────────────────────────────────────────────
  makeSample("qr-055", "testing-qa",
    "单元测试验证单个函数或模块的正确性，是测试金字塔的基础",
    "Unit testing verifies individual functions or modules, forming the base of the test pyramid",
    "explain",
    "请解释测试金字塔的三个层次及其比例关系。",
    [
      { key: "tp-unit", criterion: "解释单元测试层", expectedConcept: "数量最多/速度最快", weight: 2, required: true },
      { key: "tp-integration", criterion: "解释集成测试层", expectedConcept: "验证模块间交互", weight: 2, required: true },
      { key: "tp-e2e", criterion: "解释端到端测试层", expectedConcept: "数量最少/速度最慢", weight: 2, required: true },
    ],
  ),
  makeSample("qr-056", "testing-qa",
    "Mock 和 Stub 是测试替身的不同类型，用于隔离被测单元",
    "Mock and Stub are types of test doubles for isolating units under test",
    "explain",
    "请区分 Mock 和 Stub 的区别，并各举一个使用场景。",
    [
      { key: "stub-def", criterion: "定义 Stub", expectedConcept: "提供预设返回值", weight: 2, required: true },
      { key: "mock-def", criterion: "定义 Mock", expectedConcept: "验证交互行为", weight: 2, required: true },
      { key: "stub-mock-diff", criterion: "说明核心区别", expectedConcept: "Stub关注状态/Mock关注行为", weight: 3, required: true },
    ],
  ),
  makeSample("qr-057", "testing-qa",
    "代码覆盖率衡量测试覆盖的代码行、分支和路径比例",
    "Code coverage measures the proportion of code lines, branches, and paths covered by tests",
    "apply",
    "给定一个 if-else 分支，请说明如何达到 100% 分支覆盖率。",
    [
      { key: "cov-branch", criterion: "解释分支覆盖", expectedConcept: "每个分支都执行到", weight: 2, required: true },
      { key: "cov-test", criterion: "描述测试用例", expectedConcept: "为true和false各写一个测试", weight: 2, required: true },
      { key: "cov-limit", criterion: "说明覆盖率局限性", expectedConcept: "高覆盖率不等于高质量", weight: 2, required: false },
    ],
  ),
  makeSample("qr-058", "testing-qa",
    "属性测试(Property-Based Testing)通过随机生成输入验证不变量",
    "Property-based testing verifies invariants with randomly generated inputs",
    "explain",
    "请解释属性测试与传统示例测试的区别。",
    [
      { key: "pbt-principle", criterion: "解释属性测试原理", expectedConcept: "声明不变量随机输入验证", weight: 2, required: true },
      { key: "pbt-vs-example", criterion: "对比示例测试", expectedConcept: "示例测试固定输入/属性测试随机", weight: 3, required: true },
      { key: "pbt-shrink", criterion: "解释缩减", expectedConcept: "失败后自动找最小复现", weight: 2, required: false },
    ],
  ),
  makeSample("qr-059", "testing-qa",
    "契约测试验证服务间接口的兼容性，防止 API 变更破坏消费者",
    "Contract testing verifies interface compatibility between services",
    "explain",
    "请解释消费者驱动的契约测试(Consumer-Driven Contract Testing)的工作原理。",
    [
      { key: "ct-consumer", criterion: "解释消费者驱动", expectedConcept: "消费者定义期望契约", weight: 2, required: true },
      { key: "ct-provider", criterion: "解释提供者验证", expectedConcept: "提供者运行契约验证", weight: 2, required: true },
      { key: "ct-benefit", criterion: "说明好处", expectedConcept: "独立部署/API变更安全", weight: 2, required: true },
    ],
  ),
  makeSample("qr-060", "testing-qa",
    "突变测试(Mutation Testing)通过注入代码缺陷来衡量测试有效性",
    "Mutation testing measures test effectiveness by injecting code defects",
    "explain",
    "请解释突变测试的工作原理及突变分数(Mutation Score)的含义。",
    [
      { key: "mt-mutant", criterion: "解释突变体", expectedConcept: "故意修改代码制造缺陷", weight: 2, required: true },
      { key: "mt-kill", criterion: "解释杀死突变", expectedConcept: "测试失败说明突变被杀死", weight: 3, required: true },
      { key: "mt-score", criterion: "解释突变分数", expectedConcept: "杀死突变数/总突变数", weight: 2, required: true },
    ],
  ),
];

// ─── 验证函数 ─────────────────────────────────────────────────────────────

export function getQuestionRubricGoldStats() {
  const total = QUESTION_RUBRIC_GOLD.length;
  const byDomain = DOMAINS.reduce((acc, domain) => {
    acc[domain] = QUESTION_RUBRIC_GOLD.filter((s) => s.domain === domain).length;
    return acc;
  }, {} as Record<string, number>);
  const accepted = QUESTION_RUBRIC_GOLD.filter((s) => s.humanAccepted).length;
  const leaked = QUESTION_RUBRIC_GOLD.filter((s) => s.leakageReason !== null).length;
  const totalRubricItems = QUESTION_RUBRIC_GOLD.reduce(
    (sum, s) => sum + s.expectedRubricItems.length, 0,
  );

  return {
    total,
    byDomain,
    accepted,
    leaked,
    totalRubricItems,
    meetsMinimumSize: total >= QUESTION_RUBRIC_GOLD_MINIMUM_SIZE,
  };
}
