import type { PetJourneyPresentationV2 } from "./pet-journey-contracts";

export interface PetJourneyStoryFrameV2 {
  frameId: string;
  sequence: number;
  chapter: "初次见面" | "建立偏好" | "材料接力" | "三分钟巩固" | "保护边界";
  label: string;
  note: string;
  presentation: PetJourneyPresentationV2;
}

export const PET_JOURNEY_STORY_FRAMES: readonly PetJourneyStoryFrameV2[] = [
  {
    frameId: "first-invitation",
    sequence: 1,
    chapter: "初次见面",
    label: "一次性首邀",
    note: "三个同级入口，不抢焦点；“稍后”只延期，不等于跳过。",
    presentation: {
      kind: "invitation",
      presentationId: "pet-presentation-invitation",
      messageId: "assistant-message-invitation",
      accountPermitId: "invitation-permit-demo",
      message: "嗨，我会在你需要时帮你把资料变成一次次能完成的小行动。想从哪里开始？",
      contextLabel: "第一次见面",
      characterPresentation: "invite",
      speechMode: "speak_message",
      dismissPolicy: "explicit",
      choices: [
        {
          choiceId: "own-material",
          label: "用我的资料走一遍",
          branch: "own_material",
          description: "导入一份真实资料，完成第一条学习闭环",
        },
        {
          choiceId: "sample",
          label: "体验 90 秒示例",
          branch: "sample",
          description: "使用隔离示例，不写入正式学习记录",
        },
        {
          choiceId: "self-explore",
          label: "我先自己看看",
          branch: "self_explore",
          description: "直接进入工作区，需要时再叫我",
        },
      ],
      deferLabel: "稍后再问我",
    },
  },
  {
    frameId: "goal-preference",
    sequence: 2,
    chapter: "建立偏好",
    label: "当前目标",
    note: "目标可跳过；未选择不会阻塞进入产品。",
    presentation: {
      kind: "preference",
      presentationId: "pet-presentation-goal",
      messageId: "assistant-message-goal",
      message: "先告诉我你最近最想推进什么。我只用它安排建议，不会替你修改学习记录。",
      contextLabel: "设置相处方式",
      characterPresentation: "invite",
      speechMode: "text_only",
      dismissPolicy: "explicit",
      preference: "goal",
      step: 1,
      stepCount: 3,
      defaultValue: "build_system",
      skipLabel: "暂不设置",
      choices: [
        { choiceId: "goal-system", value: "build_system", label: "搭知识体系", description: "从材料到可复习结构" },
        { choiceId: "goal-exam", value: "prepare_exam", label: "准备考试", description: "围绕薄弱点安排巩固" },
        { choiceId: "goal-project", value: "solve_project", label: "解决项目问题", description: "让知识尽快进入应用" },
      ],
    },
  },
  {
    frameId: "intervention-preference",
    sequence: 3,
    chapter: "建立偏好",
    label: "陪伴强度",
    note: "账号级显式偏好；默认适中，模型推断不能代填。",
    presentation: {
      kind: "preference",
      presentationId: "pet-presentation-intervention",
      messageId: "assistant-message-intervention",
      message: "你希望我多主动一点，还是安静等你来找？之后随时可以改。",
      contextLabel: "设置相处方式",
      characterPresentation: "idle",
      speechMode: "text_only",
      dismissPolicy: "explicit",
      preference: "intervention_level",
      step: 2,
      stepCount: 3,
      defaultValue: "moderate",
      skipLabel: "使用默认",
      choices: [
        { choiceId: "quiet", value: "quiet", label: "安静", description: "只响应我的召唤" },
        { choiceId: "moderate", value: "moderate", label: "适中", description: "只提醒真正重要的事", recommended: true },
        { choiceId: "active", value: "active", label: "积极", description: "在合适时机给出建议" },
      ],
    },
  },
  {
    frameId: "response-preference",
    sequence: 4,
    chapter: "建立偏好",
    label: "回答偏好",
    note: "默认自适应；语音和文字只是入口偏好，不改变可信边界。",
    presentation: {
      kind: "preference",
      presentationId: "pet-presentation-response",
      messageId: "assistant-message-response",
      message: "最后一个：遇到需要你表达理解的任务，先给你哪种方式？",
      contextLabel: "设置相处方式",
      characterPresentation: "listen",
      speechMode: "text_only",
      dismissPolicy: "explicit",
      preference: "response_mode",
      step: 3,
      stepCount: 3,
      defaultValue: "adaptive",
      skipLabel: "使用默认",
      choices: [
        { choiceId: "adaptive", value: "adaptive", label: "自适应", description: "根据任务给最低摩擦方式", recommended: true },
        { choiceId: "voice", value: "voice", label: "优先语音", description: "先口述，再确认逐字稿" },
        { choiceId: "text", value: "text", label: "优先文字", description: "直接写下自己的理解" },
      ],
    },
  },
  {
    frameId: "source-waiting",
    sequence: 5,
    chapter: "材料接力",
    label: "等待解析",
    note: "资料已排队但尚未开始；不伪造进度，允许离开并等待真实通知。",
    presentation: {
      kind: "progress",
      presentationId: "pet-presentation-source-waiting",
      messageId: "assistant-message-source-waiting",
      message: "《认知心理学·记忆》已经进入解析队列。现在还没有进度可报告，你可以先去做别的。",
      contextLabel: "材料接力",
      characterPresentation: "idle",
      speechMode: "text_only",
      dismissPolicy: "persistent_until_result",
      progress: {
        state: "waiting",
        sourceName: "认知心理学·记忆.pdf",
        statusLabel: "等待系统开始解析",
        detail: "已安全接收 · 尚未取得处理回执",
        percent: null,
      },
      actions: [
        { actionId: "leave-source-waiting", kind: "leave_and_notify", label: "开始后告诉我", primary: true },
      ],
    },
  },
  {
    frameId: "source-processing",
    sequence: 6,
    chapter: "材料接力",
    label: "解析等待",
    note: "等待真实 source.ready；用户可以离开，伴星通过持久投递回来通知。",
    presentation: {
      kind: "progress",
      presentationId: "pet-presentation-source-processing",
      messageId: "assistant-message-source-processing",
      message: "《认知心理学·记忆》已经收到。我在等系统完成解析，你不用守着这里。",
      contextLabel: "材料接力",
      characterPresentation: "analyze",
      speechMode: "text_only",
      dismissPolicy: "persistent_until_result",
      progress: {
        state: "processing",
        sourceName: "认知心理学·记忆.pdf",
        statusLabel: "正在建立可追溯结构",
        detail: "抽取段落与来源位置 · 已用 18 秒",
        percent: null,
      },
      actions: [
        { actionId: "leave-source", kind: "leave_and_notify", label: "完成后告诉我", primary: true },
      ],
    },
  },
  {
    frameId: "source-failed",
    sequence: 7,
    chapter: "材料接力",
    label: "解析失败与重试",
    note: "明确失败影响；重试是可逆 UI 意图，不声称已经重新排队。",
    presentation: {
      kind: "progress",
      presentationId: "pet-presentation-source-failed",
      messageId: "assistant-message-source-failed",
      message: "这次解析没有成功。原文件仍然保留，尚未生成笔记或学习卡。",
      contextLabel: "材料接力",
      characterPresentation: "uncertain",
      speechMode: "text_only",
      dismissPolicy: "explicit",
      progress: {
        state: "failed",
        sourceName: "认知心理学·记忆.pdf",
        statusLabel: "解析未完成",
        detail: "未写入笔记与学习卡 · 可以安全重试",
        percent: null,
      },
      actions: [
        { actionId: "retry-source", kind: "retry", label: "重新尝试", primary: true },
        { actionId: "open-source-failed", kind: "open_source", label: "查看原文件" },
      ],
    },
  },
  {
    frameId: "source-ready",
    sequence: 8,
    chapter: "材料接力",
    label: "解析完成",
    note: "只有 source.ready 真事件到达后，才允许说“已完成”并打开精确资料。",
    presentation: {
      kind: "progress",
      presentationId: "pet-presentation-source-ready",
      messageId: "assistant-message-source-ready",
      message: "资料已经解析好，关键段落也保留了出处。现在可以从第一条笔记开始。",
      contextLabel: "材料接力",
      characterPresentation: "encourage",
      speechMode: "speak_message",
      dismissPolicy: "explicit",
      progress: {
        state: "ready",
        sourceName: "认知心理学·记忆.pdf",
        statusLabel: "解析完成",
        detail: "42 个来源片段 · 8 个候选知识点",
        percent: 100,
      },
      actions: [
        { actionId: "open-source", kind: "open_source", label: "打开这份资料", primary: true },
      ],
    },
  },
  {
    frameId: "run-proposal",
    sequence: 9,
    chapter: "三分钟巩固",
    label: "Run 提议",
    note: "解释目标、时间与证明边界；此时还没有开始 Run。",
    presentation: {
      kind: "run_proposal",
      presentationId: "pet-presentation-run-proposal",
      messageId: "assistant-message-run-proposal",
      message: "这张卡已经适合做一次短巩固。我可以带你用自己的话讲清“提取练习为什么有效”。",
      contextLabel: "下一步建议",
      characterPresentation: "navigate",
      speechMode: "speak_message",
      dismissPolicy: "explicit",
      proposalId: "proposal-start-run-demo",
      target: "提取练习",
      targetDetail: "解释机制，并举一个与你学习有关的例子",
      estimatedMinutes: 3,
      proofBoundary: "独立作答后才会评估理解；提示后完成只记练习",
      scheduleBoundary: "仅可信 Commit 才可能创建首次复习",
      primaryLabel: "看看怎么进行",
      secondaryLabel: "这次不了",
    },
  },
  {
    frameId: "run-confirmation",
    sequence: 10,
    chapter: "三分钟巩固",
    label: "动作确认",
    note: "Typed proposal 的最后授权点；未确认前不创建 Run、不修改状态。",
    presentation: {
      kind: "confirmation",
      presentationId: "pet-presentation-confirmation",
      messageId: "assistant-message-confirmation",
      message: "确认后，我会为当前知识点创建一条三分钟巩固旅程，并把主窗口带到正式任务。",
      contextLabel: "需要你的确认",
      characterPresentation: "listen",
      speechMode: "text_only",
      dismissPolicy: "persistent_until_result",
      proposalId: "proposal-start-run-demo",
      actionName: "开始三分钟巩固",
      target: "提取练习 · 解释与举例",
      impactSummary: "创建一个 LearningRun；不会自动作答，也不会立即改变掌握度或复习时间。",
      boundaryNote: "正式作答时我会保持静默，提交后再回来说明真实结果。",
      confirmLabel: "确认并打开任务",
      rejectLabel: "取消",
    },
  },
  {
    frameId: "run-executing",
    sequence: 11,
    chapter: "三分钟巩固",
    label: "执行与回执",
    note: "导航和 Run 创建由 ActionRun 回执推进；离开不取消后台动作。",
    presentation: {
      kind: "execution",
      presentationId: "pet-presentation-execution",
      messageId: "assistant-message-execution",
      message: "正在准备你的任务。页面真正打开后我再告诉你，不会提前假装完成。",
      contextLabel: "正在执行",
      characterPresentation: "analyze",
      speechMode: "text_only",
      dismissPolicy: "persistent_until_result",
      actionRunId: "action-run-start-learning-demo",
      statusLabel: "正在准备 LearningRun",
      detail: "目标与作答方式已冻结；正在等待页面 ready 回执",
      steps: [
        { stepId: "run-created", label: "创建任务", state: "complete" },
        { stepId: "route-open", label: "打开主窗口", state: "active" },
        { stepId: "page-ready", label: "确认页面就绪", state: "pending" },
      ],
      leaveLabel: "先收起，完成后告诉我",
    },
  },
  {
    frameId: "formal-answer-silence",
    sequence: 12,
    chapter: "保护边界",
    label: "正式作答静默",
    note: "本地硬抑制：无气泡、无提示、无主动 delivery；Run 继续独立完成。",
    presentation: {
      kind: "silent",
      presentationId: "pet-presentation-formal-silence",
      reason: "formal_answer",
      characterPresentation: "idle",
      resumePolicy: "after_artifact_lock",
    },
  },
  {
    frameId: "real-result",
    sequence: 13,
    chapter: "三分钟巩固",
    label: "真实结果收尾",
    note: "只引用 run.completed 与 Commit/Projection 结果，不用聊天模型猜测学习变化。",
    presentation: {
      kind: "result",
      presentationId: "pet-presentation-result",
      messageId: "assistant-message-result",
      message: "完成了。你已经讲清提取练习如何强化检索路径；例子里的时间间隔还可以更具体。",
      contextLabel: "巩固结果",
      characterPresentation: "celebrate",
      speechMode: "speak_message",
      dismissPolicy: "explicit",
      resultRef: "learning-run-result-demo",
      outcome: "demonstrated",
      outcomeLabel: "已证明核心理解",
      proof: "能解释主动提取比重复阅读更能暴露缺口，并说明反馈的作用。",
      gap: "下一次可补充：间隔多久、如何根据遗忘调整频率。",
      schedule: { changed: true, label: "首次复习已安排在 2 天后" },
      primaryAction: { actionId: "view-change", label: "看看星图变化", kind: "view_star_change" },
    },
  },
  {
    frameId: "partial-result",
    sequence: 14,
    chapter: "三分钟巩固",
    label: "部分成立",
    note: "只陈述已经出现的证据；缺失部分不包装成掌握。",
    presentation: {
      kind: "result",
      presentationId: "pet-presentation-result-partial",
      messageId: "assistant-message-result-partial",
      message: "你已经说明反馈能暴露缺口；但主动提取如何强化检索路径，这次还没有讲清。",
      contextLabel: "巩固结果",
      characterPresentation: "encourage",
      speechMode: "text_only",
      dismissPolicy: "explicit",
      resultRef: "learning-run-result-partial-demo",
      outcome: "partial",
      outcomeLabel: "部分理解已有证据",
      proof: "能说明及时反馈用于发现错误，并举出了错题回看的例子。",
      gap: "仍需解释：为什么先尝试回忆，比直接重读更能强化后续检索。",
      schedule: { changed: false, label: "未改变掌握度或复习时间" },
      primaryAction: { actionId: "return-partial", label: "回到学习卡补一眼", kind: "return_to_card" },
    },
  },
  {
    frameId: "practice-result",
    sequence: 15,
    chapter: "三分钟巩固",
    label: "提示后练习",
    note: "提示后完成只记练习，不升级为独立证明。",
    presentation: {
      kind: "result",
      presentationId: "pet-presentation-result-practice",
      messageId: "assistant-message-result-practice",
      message: "这轮已经练完。因为中途看过提示，我只把它记作一次练习，不把它说成独立掌握。",
      contextLabel: "巩固结果",
      characterPresentation: "encourage",
      speechMode: "text_only",
      dismissPolicy: "explicit",
      resultRef: "learning-run-result-practice-demo",
      outcome: "practice_completed",
      outcomeLabel: "已完成一次辅助练习",
      proof: "在关键词提示后，完成了机制说明和一个学习场景例子。",
      gap: "下次不看提示再讲一次，才足以形成独立理解证据。",
      schedule: { changed: false, label: "没有据此改变掌握度或复习时间" },
      primaryAction: { actionId: "return-practice", label: "返回学习卡", kind: "return_to_card" },
    },
  },
  {
    frameId: "skipped-result",
    sequence: 16,
    chapter: "三分钟巩固",
    label: "本次跳过",
    note: "跳过是用户自主退出，不生成理解结论。",
    presentation: {
      kind: "result",
      presentationId: "pet-presentation-result-skipped",
      messageId: "assistant-message-result-skipped",
      message: "这次已经按你的选择跳过。我没有获得作答证据，也不会据此判断你懂或不懂。",
      contextLabel: "巩固结果",
      characterPresentation: "idle",
      speechMode: "text_only",
      dismissPolicy: "explicit",
      resultRef: "learning-run-result-skipped-demo",
      outcome: "skipped",
      outcomeLabel: "本次已跳过",
      proof: "只记录了用户主动跳过；没有形成可评估回答。",
      gap: null,
      schedule: { changed: false, label: "未消费原复习计划，也未创建新安排" },
      primaryAction: { actionId: "return-skipped", label: "返回学习卡", kind: "return_to_card" },
    },
  },
  {
    frameId: "declared-unable-result",
    sequence: 17,
    chapter: "三分钟巩固",
    label: "明确不会",
    note: "尊重“我不会”，记录困难但不擅自承诺排程变化。",
    presentation: {
      kind: "result",
      presentationId: "pet-presentation-result-unable",
      messageId: "assistant-message-result-unable",
      message: "收到，你明确表示现在不会。我会把这次困难保留下来，但不会假装已经为你改了复习安排。",
      contextLabel: "巩固结果",
      characterPresentation: "listen",
      speechMode: "text_only",
      dismissPolicy: "explicit",
      resultRef: "learning-run-result-unable-demo",
      outcome: "declared_unable",
      outcomeLabel: "已记录当前困难",
      proof: "记录了用户明确选择“我不会”；这不是错误答案，也不是理解证据。",
      gap: "尚未确认困难来自概念、术语还是例子，需要下一次从更低摩擦入口开始。",
      schedule: { changed: false, label: "当前 UI 预览没有排程授权，不声称已调整复习" },
      primaryAction: { actionId: "return-unable", label: "回到卡片看核心解释", kind: "return_to_card" },
    },
  },
  {
    frameId: "not-assessable-result",
    sequence: 18,
    chapter: "三分钟巩固",
    label: "暂不可评估",
    note: "保存事实与评估结论分开；不可评估时不给掌握标签。",
    presentation: {
      kind: "result",
      presentationId: "pet-presentation-result-not-assessable",
      messageId: "assistant-message-result-not-assessable",
      message: "回答已经保存，但这次信息不足，暂时不能形成可信的理解判断。",
      contextLabel: "巩固结果",
      characterPresentation: "uncertain",
      speechMode: "text_only",
      dismissPolicy: "explicit",
      resultRef: "learning-run-result-not-assessable-demo",
      outcome: "not_assessable",
      outcomeLabel: "暂不可评估",
      proof: "回答内容已保存；评估没有产生可提交的掌握结论。",
      gap: "需要补充一段完整解释，或在语音逐字稿确认后重新评估。",
      schedule: { changed: false, label: "没有 Commit，因此没有改变学习状态" },
      primaryAction: { actionId: "view-evidence-unassessed", label: "查看已保存回答", kind: "view_evidence" },
    },
  },
  {
    frameId: "recoverable-error",
    sequence: 19,
    chapter: "保护边界",
    label: "可恢复错误",
    note: "说明真实影响与恢复步骤；不会声称学习记录已改变。",
    presentation: {
      kind: "recovery",
      presentationId: "pet-presentation-recovery",
      messageId: "assistant-message-recovery",
      message: "评估服务刚才没有返回结果。你的回答已经安全保存，但目前还没有写入掌握度或复习时间。",
      contextLabel: "需要恢复",
      characterPresentation: "uncertain",
      speechMode: "text_only",
      dismissPolicy: "explicit",
      errorCode: "ASSESSMENT_TEMPORARILY_UNAVAILABLE",
      title: "回答已保存，评估尚未完成",
      impact: "Artifact 已锁定；没有 Commit，也没有消费原复习计划。",
      recovery: "可以重试评估，或先离开，系统恢复后会通过同一条对话通知你。",
      retryLabel: "重试评估",
      dismissLabel: "先离开",
    },
  },
  {
    frameId: "dnd-suppressed",
    sequence: 20,
    chapter: "保护边界",
    label: "勿扰抑制",
    note: "DND 总是抑制主动 cue；不会为了提示用户“正在勿扰”而再弹一只气泡。",
    presentation: {
      kind: "silent",
      presentationId: "pet-presentation-dnd",
      reason: "dnd",
      characterPresentation: "idle",
      resumePolicy: "when_availability_online",
    },
  },
];

export function getPetJourneyStoryFrame(frameId: string): PetJourneyStoryFrameV2 {
  return PET_JOURNEY_STORY_FRAMES.find((frame) => frame.frameId === frameId) ?? PET_JOURNEY_STORY_FRAMES[0];
}
